import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';
import 'package:oplin/bloc/todo_view_filter.dart';
import 'package:oplin/db/models.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'todo_event.freezed.dart';

// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'todo_event.g.dart';

@freezed
class TodoEvent with _$TodoEvent {
  const factory TodoEvent.subscriptionRequested() = SubscriptionRequested;

  const factory TodoEvent.completionToggled(Todo todo, bool isCompleted) =
      CompletionToggled;

  const factory TodoEvent.deleted(Todo todo) = Deleted;

  const factory TodoEvent.unDoDeleted() = UnDoDeleted;

  const factory TodoEvent.filterChanged(TodoViewFilter filter) = FilterChanged;

  const factory TodoEvent.search(String? search) = Search;

  const factory TodoEvent.toggleAll() = ToggleAll;

  const factory TodoEvent.clearCompleted() = ClearCompleted;

  factory TodoEvent.fromJson(Map<String, Object?> json) =>
      _$TodoEventFromJson(json);
}
