appId: com.github.springeye.oplin
# relative path to the application's icon
icon: 1024x1024.png

script:
  - echo 'Running a Script'

include: [ ]
exclude: [ ]
# its true by default
default_excludes: true

files:
  include: [ ]
  exclude: [ ]
  # its true by default
  default_excludes: true
