# This is a development snapcraft file, no version is specified. Uncomment the line below to build a snap.
#version: "0.1.0"
name: oplin
summary: Oplin Notebook
description: |
  A sample Notebook Application.

confinement: strict
base: core18
grade: stable
icon: snap/gui/oplin.png

apps:
  oplin:
    command: desktop-launch oplin
    extensions: [ flutter-stable ]
    plugs:
      - network
      - desktop
      - home

parts:
  oplin:
    source: https://github.com/springeye/oplin.git
    plugin: flutter
    flutter-target: lib/main.dart
