name: build linux
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  linux:
    name: build on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.0.0'
      - run: sudo apt-get update && sudo apt-get install ninja-build libgtk-3-dev -y
      - run: flutter config --enable-linux-desktop
      - run: flutter doctor -v
      - run: flutter pub get
      - run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: build linux
        run: flutter build linux -v
