name: build macos
on:
  push:
    branches:
      - master
  pull_request:

jobs:

  macos:
    name: build on  macos-latest
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11.x'
      - name: Clone Flutter repository
        uses: subosito/flutter-action@v1.5.3
        with:
          channel: stable
          flutter-version: '3.0.0'
      - run: flutter config --enable-macos-desktop
      - run: flutter doctor -v
      - run: flutter pub get
      - run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: build macos
        run: flutter build macos -v

