name: build macos
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  macos:
    name: build on macos-latest
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: kuhnroyal/flutter-fvm-config-action@v1
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.FLUTTER_CHANNEL }}
          flutter-version: ${{ env.FLUTTER_VERSION }}
      - run: flutter config --enable-macos-desktop
      - run: flutter doctor -v
      - run: flutter pub get
      - run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: build macos
        run: flutter pub run flutter_distributor:main release --name prod-macos

