name: build windows
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  windows:
    name: build on windows-latest
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11.x'
      - name: Clone Flutter repository
        uses: subosito/flutter-action@v1.5.3
        with:
          channel: stable
          flutter-version: '3.0.0'
      - run: flutter config --enable-windows-desktop
      - run: flutter doctor -v
      - run: flutter pub get
      - run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: build windows
        run: flutter build windows -v

