name: build windows
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  windows:
    name: build on windows-latest
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: kuhnroyal/flutter-fvm-config-action@v1
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.FLUTTER_CHANNEL }}
          flutter-version: ${{ env.FLUTTER_VERSION }}
      - run: flutter config --enable-windows-desktop
      - run: flutter doctor
      - run: flutter pub get
      - run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: build windows
        run: flutter pub run flutter_distributor:main release --name prod-windows

